from PyQt5 import QtCore, QtGui, QtWidgets
from register import RegisterWindow

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        self.Dialog = Dialog  # Dialog referansını saklıyoruz
        Dialog.setObjectName("Dialog")
        Dialog.resize(413, 353)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit_kullaniciadigiris = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_kullaniciadigiris.sizePolicy().hasHeightForWidth())
        self.lineEdit_kullaniciadigiris.setSizePolicy(sizePolicy)
        self.lineEdit_kullaniciadigiris.setObjectName("lineEdit_kullaniciadigiris")
        self.horizontalLayout_3.addWidget(self.lineEdit_kullaniciadigiris)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_sifregiris = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_sifregiris.sizePolicy().hasHeightForWidth())
        self.lineEdit_sifregiris.setSizePolicy(sizePolicy)
        self.lineEdit_sifregiris.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_sifregiris.setObjectName("lineEdit_sifregiris")
        self.horizontalLayout_2.addWidget(self.lineEdit_sifregiris)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_kayitol_giris = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_kayitol_giris.sizePolicy().hasHeightForWidth())
        self.pushButton_kayitol_giris.setSizePolicy(sizePolicy)
        self.pushButton_kayitol_giris.setObjectName("pushButton_kayitol_giris")
        self.horizontalLayout.addWidget(self.pushButton_kayitol_giris)
        self.pushButton_girisYap = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_girisYap.sizePolicy().hasHeightForWidth())
        self.pushButton_girisYap.setSizePolicy(sizePolicy)
        self.pushButton_girisYap.setObjectName("pushButton_girisYap")
        self.horizontalLayout.addWidget(self.pushButton_girisYap)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        # Kayıt Ol butonuna tıklandığında register penceresini açma
        self.pushButton_kayitol_giris.clicked.connect(self.open_register_window)

        # Giriş Yap butonuna tıklandığında login metodunu çağırma
        self.pushButton_girisYap.clicked.connect(self.login)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Kullanıcı Adı: "))
        self.label_2.setText(_translate("Dialog", "Şifre: "))
        self.pushButton_kayitol_giris.setText(_translate("Dialog", "Kayıt Ol"))
        self.pushButton_girisYap.setText(_translate("Dialog", "Giriş Yap"))

    def open_register_window(self):
        self.register_window = RegisterWindow()
        self.register_window.exec_()

    def login(self):
        from login import login_user
        login_user(self)
