# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(318, 244)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_kullaniciadi_kayit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_kullaniciadi_kayit.setObjectName("lineEdit_kullaniciadi_kayit")
        self.gridLayout_2.addWidget(self.lineEdit_kullaniciadi_kayit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_sifre_kayit1 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_sifre_kayit1.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEdit_sifre_kayit1.setObjectName("lineEdit_sifre_kayit1")
        self.gridLayout_2.addWidget(self.lineEdit_sifre_kayit1, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_sifre_kayit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_sifre_kayit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_sifre_kayit_2.setObjectName("lineEdit_sifre_kayit_2")
        self.gridLayout_2.addWidget(self.lineEdit_sifre_kayit_2, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.pushButton_kayitol_kayit = QtWidgets.QPushButton(Form)
        self.pushButton_kayitol_kayit.setObjectName("pushButton_kayitol_kayit")
        self.verticalLayout.addWidget(self.pushButton_kayitol_kayit)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Kayıt Ol"))
        self.label.setText(_translate("Form", "Kullanıcı Adı: "))
        self.label_2.setText(_translate("Form", "Şifre: "))
        self.label_3.setText(_translate("Form", "Şifre: "))
        self.pushButton_kayitol_kayit.setText(_translate("Form", "Kayıt Ol"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
