# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResultWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1137, 467)
        self.progressBar_sonuclar = QtWidgets.QProgressBar(Dialog)
        self.progressBar_sonuclar.setGeometry(QtCore.QRect(190, 70, 771, 23))
        self.progressBar_sonuclar.setProperty("value", 0)
        self.progressBar_sonuclar.setObjectName("progressBar_sonuclar")
        self.treeWidget_sonuclar = QtWidgets.QTreeWidget(Dialog)
        self.treeWidget_sonuclar.setGeometry(QtCore.QRect(30, 110, 1071, 261))
        self.treeWidget_sonuclar.setObjectName("treeWidget_sonuclar")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(450, 400, 194, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_kaydetme = QtWidgets.QPushButton(self.widget)
        self.pushButton_kaydetme.setObjectName("pushButton_kaydetme")
        self.horizontalLayout.addWidget(self.pushButton_kaydetme)
        self.pushButton_kaydet = QtWidgets.QPushButton(self.widget)
        self.pushButton_kaydet.setObjectName("pushButton_kaydet")
        self.horizontalLayout.addWidget(self.pushButton_kaydet)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.treeWidget_sonuclar.headerItem().setText(0, _translate("Dialog", "Epoch"))
        self.treeWidget_sonuclar.headerItem().setText(1, _translate("Dialog", "Train Loss"))
        self.treeWidget_sonuclar.headerItem().setText(2, _translate("Dialog", "Train Acc"))
        self.treeWidget_sonuclar.headerItem().setText(3, _translate("Dialog", "Train Precision"))
        self.treeWidget_sonuclar.headerItem().setText(4, _translate("Dialog", "Train Recall"))
        self.treeWidget_sonuclar.headerItem().setText(5, _translate("Dialog", "Train F1"))
        self.treeWidget_sonuclar.headerItem().setText(6, _translate("Dialog", "Test Loss"))
        self.treeWidget_sonuclar.headerItem().setText(7, _translate("Dialog", "Test Acc"))
        self.treeWidget_sonuclar.headerItem().setText(8, _translate("Dialog", "Test Precision"))
        self.treeWidget_sonuclar.headerItem().setText(9, _translate("Dialog", "Test Recall"))
        self.treeWidget_sonuclar.headerItem().setText(10, _translate("Dialog", "Test F1"))
        self.pushButton_kaydetme.setText(_translate("Dialog", "Kaydetme"))
        self.pushButton_kaydet.setText(_translate("Dialog", "Kaydet"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
